### PR TITLE
Remove the leading hyphen if tag is not available

### PR DESCRIPTION
**Pull request by chrisun**

### CODE REVIEW

**Review by alan2112000 — COMMENTED** [review]
Should we update the version also? 
although we did not build the staging directly

**Comment by chrisun** [comment]
@alan2112000 I bumped up the version, though it'd probably conflict with #3 ...

**Review by alan2112000 — APPROVED** [review]
i'm good but I assign as the reviewer also, since there is no one wana review my code, could you look that too? thanks #3

**Comment by alan2112000** [comment]
HI @chrisun you can merge it thanks.

**Pull request merged**
